package com.modofo.mofire;

public interface MoFireEventType {
	final static int POST_SUCCESS=0,POST_ERROR=1,POST_SAVE_SUCCESS=2,POST_SAVE_ERROR=3
		,SETTING_VALIDATE_ERROR=4,SETTING_VALIDATE_SUCCESS=5,
		RECORDER_STOP=6,SETTING_SAVE_SUCCESS=7,SETTING_SAVE_ERROR=8;
	
	
}
